chainornot/chainornot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("detect.urls"))
]

chainornot/detect/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index, name="index")
]

chainornot/detect/models.py
from django.db import models

# Create your models here.

chainornot/detect/forms.py
from django import forms

class SingleInputFieldForm(forms.Form):
  text_field = forms.CharField(label=False, max_length=100)

chainornot/detect/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import SingleInputFieldForm
import requests
import numpy as np
from keras.utils import load_img, img_to_array
import tensorflow as tf
from io import BytesIO
from PIL import Image
# Create your views here.

def index(request):
    if request.method == 'POST':
        form = SingleInputFieldForm(request.POST)
        if form.is_valid():
            text_value = form.cleaned_data['text_field']
            image_url = text_value
            try:
                response = requests.get(image_url, stream=True)  
                if response.status_code == 200:
                    cnn = tf.keras.models.Sequential()
                    cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64,64,3]))
                    cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
                    cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
                    cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
                    cnn.add(tf.keras.layers.Flatten())
                    cnn.add(tf.keras.layers.Dense(units=128, activation="relu"))
                    cnn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
                    cnn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
                    cnn.load_weights("/Users/patrickschwarz/Coding/kaggle/blakdetect/chainornot/detect/model.h5")
                    
                    
                    response = requests.get(image_url, stream=True)
                    response.raise_for_status()
                    img = Image.open(BytesIO(response.content))
                    img = img.convert('RGB')
                    img = img.resize((64, 64))
                    img_array = img_to_array(img)
                    img_array = tf.expand_dims(img_array, 0) 
                    result = cnn.predict(img_array)
                    price = result[0][0]*100000
                    return render(request, 'detect/results.html', {'text_value': image_url,'prediction': result[0][0]*100, 'price': price})
                else:
                    # Handle case where image download fails
                    return HttpResponse(f'Failed to download image. (Status code: {response.status_code}')
            except requests.exceptions.RequestException as e:
                # Handle other download errors
                    return HttpResponse('Error downloading image: {e}')
            return render(request, 'detect/results.html', {'text_value': text_value})
    else:
        form = SingleInputFieldForm()
    return render(request, "detect/index.html",{'form': form})

chainornot/detect/templates/detect/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Home</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:700,300);



.title {
	width: 100%;
	height: 50px;
	text-align: center;
}

h1 {
	font-size: 24px;
	font-weight: 300;
	color: #666;
}

.dropzone {
	width: 200px;
	height: 160px;
	border: 1px dashed #999;
	border-radius: 3px;
	text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
}

.upload-icon {
	margin: 25px 2px 2px 2px;
}

.upload-input {
	position: relative;
	top: -62px;
	left: 0;
	width: 100%;
	height: 100%;
	opacity: 0;
}

.btn {
	display: block;
	width: 140px;
	height: 40px;
	background: rgb(54, 54, 54);
	color: #fff;
	border-radius: 3px;
	border: 0;
	transition: all 0.3s ease-in-out;
	font-size: 14px;
}

.btn:hover {
	background: black;
    color: white;
}

    </style>
</head>
<body class="bg-gray-200">
    <header>
        <div class="flex align-center items-center h-28 shadow-md bg-white">
            <div class="container d-flex justify-content-between">
              <a href="#" class="navbar-brand d-flex align-items-center" style="display: flex; align-items: center; justify-content: center; gap: 15px;">
                <img src="https://cdn-icons-png.flaticon.com/512/475/475457.png" width="40px"/>
                  
                <h1 class="font-semibold" style="color:black; font-size: 28px; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">CHAIN OR NOT</h1>
              </a>
            </div>
          </div>
    </header>
    <div class="flex items-center justify-between h-[85vh] gap-8 p-24">
        <div class="bg-white w-full flex items-center justify-center rounded-3xl py-16 h-[75vh]">
            
                <div class="flex items-center justify-center flex-col gap-6">
                    <div class="title">
                        <h1>Add File Link</h1>
                    </div>

                    <img class="w-72 h-72 object-cover rounded-lg" src="https://st4.depositphotos.com/9998432/22597/v/450/depositphotos_225976914-stock-illustration-person-gray-photo-placeholder-man.jpg"/>
            
                    <form method="post" class="w-72">
                        {% csrf_token %}  
                        <input id="id_text_field" placeholder="Enter Image URL" name="text_field" type="text" class="w-72 border-2 border-black px-4 py-2">
                        <button class="w-72 bg-black text-white px-4 py-2 text-center mt-2" type="submit">Submit</button>
                    </form>
            
                </div>
         
        </div>
        <div class="bg-white w-full flex flex-col items-center justify-center rounded-3xl py-16 h-[75vh]">
            <div class="title">
                <h1>Add the image URL, and let's see if we can chain him up</h1>
            </div>
            <img class="w-72 h-72 object-fit" src="https://media1.tenor.com/m/I6ggVKuaWoMAAAAC/just-do-it-words-of-wisdom.gif"/>
        </div>
    </div>
</body>
</html>

chainornot/detect/templates/detect/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Result</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:700,300);



.title {
	width: 100%;
	height: 50px;
	text-align: center;
}

h1 {
	font-size: 24px;
	font-weight: 300;
	color: #666;
}

.dropzone {
	width: 200px;
	height: 160px;
	border: 1px dashed #999;
	border-radius: 3px;
	text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
}

.upload-icon {
	margin: 25px 2px 2px 2px;
}

.upload-input {
	position: relative;
	top: -62px;
	left: 0;
	width: 100%;
	height: 100%;
	opacity: 0;
}

.btn {
	display: block;
	width: 140px;
	height: 40px;
	background: rgb(54, 54, 54);
	color: #fff;
	border-radius: 3px;
	border: 0;
	transition: all 0.3s ease-in-out;
	font-size: 14px;
}

.btn:hover {
	background: black;
    color: white;
}

    </style>
</head>
<body class="bg-gray-200">
    <header>
        <div class="flex align-center items-center h-28 shadow-md bg-white">
            <div class="container d-flex justify-content-between">
              <a href="#" class="navbar-brand d-flex align-items-center" style="display: flex; align-items: center; justify-content: center; gap: 15px;">
                <img src="https://cdn-icons-png.flaticon.com/512/475/475457.png" width="40px"/>
                  
                <h1 class="font-semibold" style="color:black; font-size: 28px; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">CHAIN OR NOT</h1>
              </a>
            </div>
          </div>
    </header>
    <div class="flex items-center justify-between h-[85vh] gap-8 p-24">
        <div class="bg-white w-full flex items-center justify-center rounded-3xl py-16 h-[75vh]">
            
                <div class="flex items-center justify-center flex-col gap-6">
                    <div class="title">
                        <h1>Prediction Sucessful {{prediction}}% a Black</h1>
                    </div>

                    <img class="w-72 h-72 object-cover rounded-lg" src={{text_value}}/>
            
                    <form method="post" class="w-72">
                        {% csrf_token %}  
                        <input id="id_text_field" placeholder="Enter Image URL" name="text_field" type="text" class="w-72 border-2 border-black px-4 py-2">
                        <button class="w-72 bg-black text-white px-4 py-2 text-center mt-2" type="submit">Submit</button>
                    </form>
                    
                </div>
         
        </div>
        {% if prediction > 0 %}
        <div class="bg-white w-full flex flex-col items-center justify-center rounded-3xl py-16 gap-8 h-[75vh]">
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-3xl font-bold text-red-800">⛓️ HELL YEAH! ⛓️</h1>
                <h2 class="text-2xl font-regular text-black">CHAIN THE DAWG UP NOW!</h2>
            </div>
            <img class="w-82 h-72 object-fit" src="https://gifdb.com/images/high/slave-498-x-365-gif-61btkwnuybox8anm.gif"/>
            <h3>Starting Price : ${{price}}</h3>
        </div>
        {% else %}
        <div class="bg-white w-full flex flex-col items-center justify-center rounded-3xl py-16 gap-8 h-[75vh]">
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-3xl font-bold text-green-800">🙁 Let him go . . . 🤷</h1>
                <h2 class="text-2xl font-regular text-black">I dont think he bleck</h2>
            </div>
            <img class="w-82 h-72 object-fit" src="https://i.imgur.com/QaEMhRm.gif"/>
            <h3>Not For Sale</h3>
        </div>

        {% endif %}
    </div>
</body>
</html>